from . import pharmacy
from . import account_invoice
from . import supplier_discount
from . import credit_limit
from . import partner_payment
from . import rack_transfer
from . import partial_transfer
from . import res_partner
from . import product
from . import cheque
from . import stockpicking
